name: Release Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:


  release:
    name: Release | Shopware ${{ matrix.shopware }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shopware: [ '5.6.10' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Start Docker
        run: |
          docker run --rm -p 80:80 --name shop -d dockware/play:${{ matrix.shopware }}
          sleep 30
          docker logs shop

      - name: Upload into Docker
        run: docker cp $(pwd)/. shop:/var/www/html/custom/plugins/MollieShopware

      - name: Create ZIP File
        run: |
          docker cp shop:/var/www/html/custom/plugins/MollieShopware
          make release -B

      - name: Download ZIP File
        run: docker cp shop:/var/www/html/custom/plugins/Mollie*.zip $(pwd)/release/MollieShopware.zip

      - name: Store Relase Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress_results_sw_v${{ matrix.shopware }}
          retention-days: 1
          path: |
            $(pwd)/release/MollieShopware.zip
