name: Release Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:


  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Start Docker
        run: |
          docker run --rm -p 80:80 --name shop -d dockware/play:latest
          sleep 30
          docker logs shop

      - name: Upload into Docker
        run: docker cp $(pwd)/. shop:/var/www/html/custom/plugins/MollieShopware

      - name: Create ZIP File
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/MollieShopware && make release -B'

      - name: Download ZIP File
        run: docker cp shop:/var/www/html/custom/plugins/Mollie*.zip $(pwd)/release/MollieShopware.zip

      - name: Store Release Files
        uses: actions/upload-artifact@v2
        with:
          name: MollieShopware.zip
          retention-days: 1
          path: $(pwd)/release/MollieShopware.zip
